export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { NavBar } from "@/components/NavBar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SidebarProvider>
        <NavBar />
        <body>
          <SidebarTrigger />
          {children}
        </body>
      </SidebarProvider>
    </html>
  );
}
